DROP TABLE RDL_users;
DROP TABLE RDL_log;

CREATE TABLE RDL_users (
	`id` INT NOT NULL AUTO_INCREMENT,
	`given_name` VARCHAR(50) NOT NULL,
	`family_name` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`rank` int(2) NOT NULL DEFAULT 1,
	`added_by` VARCHAR(150) NOT NULL,
	`time_added` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);
CREATE TABLE RDL_log (
    `id` INT NOT NULL AUTO_INCREMENT,
	`given_name` VARCHAR(50) NOT NULL,
	`family_name` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`time` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);