DROP TABLE RDL_users;
DROP TABLE RDL_log;

CREATE TABLE RDL_users (
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(50) DEFAULT NULL,
	last_name VARCHAR(50) DEFAULT NULL,
	email VARCHAR(150) DEFAULT NULL,
	site_admin bit DEFAULT 0,
	PRIMARY KEY (id)
);
CREATE TABLE RDL_log (
    id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(50) DEFAULT NULL,
	last_name VARCHAR(50) DEFAULT NULL,
	email VARCHAR(150) NOT NULL,
	site_admin bit DEFAULT 0,
	`time` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);
