DROP TABLE RDL_admins;
DROP TABLE RDL_log;

CREATE TABLE RDL_admins (
	id INT NOT NULL AUTO_INCREMENT,
	given_name VARCHAR(50) DEFAULT NULL,
	family_name VARCHAR(50) DEFAULT NULL,
	email VARCHAR(150) DEFAULT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE RDL_log (
    id INT NOT NULL AUTO_INCREMENT,
	given_name VARCHAR(50) DEFAULT NULL,
	family_name VARCHAR(50) DEFAULT NULL,
	email VARCHAR(150) NOT NULL,
	`time` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);
