CREATE TABLE RDL_moderators (
	`id` INT NOT NULL AUTO_INCREMENT,
	`given_name` VARCHAR(50) NOT NULL,
	`family_name` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`admin` BOOLEAN NOT NULL DEFAULT FALSE,
	`added_by` VARCHAR(150) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE RDL_users (
	`id` INT NOT NULL AUTO_INCREMENT,
	`given_name` VARCHAR(50) NOT NULL,
	`family_name` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`added by` VARCHAR(150) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE RDL_log (
    `id` INT NOT NULL AUTO_INCREMENT,
	`given_name` VARCHAR(50) NOT NULL,
	`family_name` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`time` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);